from selenium.webdriver.edge.webdriver import WebDriver
from selenium.webdriver.common.by import By
from django.contrib.auth.models import User
from django.test import LiveServerTestCase
from users.models import CustomUser
import time

# Tests for edit user feature
class EditUserTests(LiveServerTestCase):

    def setUp(self):
        ### Setup test data
        self.password = 'pass12345'
        self.user = User.objects.create_user(username='test1', password=self.password, first_name='first', last_name='last', email='test1@email.com')
        self.profile = CustomUser.objects.create(user=self.user, phone_number='1-222-333-4444')

        ### Setup webdriver
        self.driver = WebDriver()

    def tearDown(self):
        self.driver.close()
        User.objects.all().delete()
        CustomUser.objects.all().delete()

    ## Test edit user feature with empty username
    def test_edit_user_feature_empty_username(self):
        self.driver.get(self.live_server_url)
        self.driver.find_element(By.NAME, 'username').send_keys(self.user.username)
        self.driver.find_element(By.NAME, 'password').send_keys(self.password)
        self.driver.find_element(By.ID, 'loginButton').click()
        self.driver.find_element(By.ID, 'manageInfoButton').click()
        username = self.driver.find_element(By.NAME, 'username')
        username.clear()
        username.send_keys('')
        first_name = self.driver.find_element(By.NAME, 'first_name')
        first_name.clear()
        first_name.send_keys('updated')
        last_name = self.driver.find_element(By.NAME, 'last_name')
        last_name.clear()
        last_name.send_keys('updated')
        email = self.driver.find_element(By.NAME, 'email')
        email.clear()
        email.send_keys('updated@email.com')
        phone_number = self.driver.find_element(By.NAME, 'phone_number')
        phone_number.clear()
        phone_number.send_keys('4-333-222-1111')
        self.driver.find_element(By.ID, 'updateUserButton').click()
        self.assertEqual(self.driver.title, 'Updating Information')

    ## Test edit user feature with empty first name
    def test_edit_user_feature_empty_first_name(self):
        self.driver.get(self.live_server_url)
        self.driver.find_element(By.NAME, 'username').send_keys(self.user.username)
        self.driver.find_element(By.NAME, 'password').send_keys(self.password)
        self.driver.find_element(By.ID, 'loginButton').click()
        self.driver.find_element(By.ID, 'manageInfoButton').click()
        username = self.driver.find_element(By.NAME, 'username')
        username.clear()
        username.send_keys('updated')
        first_name = self.driver.find_element(By.NAME, 'first_name')
        first_name.clear()
        first_name.send_keys('')
        last_name = self.driver.find_element(By.NAME, 'last_name')
        last_name.clear()
        last_name.send_keys('updated')
        email = self.driver.find_element(By.NAME, 'email')
        email.clear()
        email.send_keys('updated@email.com')
        phone_number = self.driver.find_element(By.NAME, 'phone_number')
        phone_number.clear()
        phone_number.send_keys('4-333-222-1111')
        self.driver.find_element(By.ID, 'updateUserButton').click()
        self.assertEqual(self.driver.title, 'Updating Information')

    ## Test edit user feature with empty last name
    def test_edit_user_feature_empty_last_name(self):
        self.driver.get(self.live_server_url)
        self.driver.find_element(By.NAME, 'username').send_keys(self.user.username)
        self.driver.find_element(By.NAME, 'password').send_keys(self.password)
        self.driver.find_element(By.ID, 'loginButton').click()
        self.driver.find_element(By.ID, 'manageInfoButton').click()
        username = self.driver.find_element(By.NAME, 'username')
        username.clear()
        username.send_keys('updated')
        first_name = self.driver.find_element(By.NAME, 'first_name')
        first_name.clear()
        first_name.send_keys('updated')
        last_name = self.driver.find_element(By.NAME, 'last_name')
        last_name.clear()
        last_name.send_keys('')
        email = self.driver.find_element(By.NAME, 'email')
        email.clear()
        email.send_keys('updated@email.com')
        phone_number = self.driver.find_element(By.NAME, 'phone_number')
        phone_number.clear()
        phone_number.send_keys('4-333-222-1111')
        self.driver.find_element(By.ID, 'updateUserButton').click()
        self.assertEqual(self.driver.title, 'Updating Information')

    ## Test edit user feature with empty email
    def test_edit_user_feature_empty_email(self):
        self.driver.get(self.live_server_url)
        self.driver.find_element(By.NAME, 'username').send_keys(self.user.username)
        self.driver.find_element(By.NAME, 'password').send_keys(self.password)
        self.driver.find_element(By.ID, 'loginButton').click()
        self.driver.find_element(By.ID, 'manageInfoButton').click()
        username = self.driver.find_element(By.NAME, 'username')
        username.clear()
        username.send_keys('updated')
        first_name = self.driver.find_element(By.NAME, 'first_name')
        first_name.clear()
        first_name.send_keys('updated')
        last_name = self.driver.find_element(By.NAME, 'last_name')
        last_name.clear()
        last_name.send_keys('updated')
        email = self.driver.find_element(By.NAME, 'email')
        email.clear()
        email.send_keys('')
        phone_number = self.driver.find_element(By.NAME, 'phone_number')
        phone_number.clear()
        phone_number.send_keys('4-333-222-1111')
        self.driver.find_element(By.ID, 'updateUserButton').click()
        self.assertEqual(self.driver.title, 'Updating Information')

    ## Test edit user feature with empty phone number
    def test_edit_user_feature_empty_phone_number(self):
        self.driver.get(self.live_server_url)
        self.driver.find_element(By.NAME, 'username').send_keys(self.user.username)
        self.driver.find_element(By.NAME, 'password').send_keys(self.password)
        self.driver.find_element(By.ID, 'loginButton').click()
        self.driver.find_element(By.ID, 'manageInfoButton').click()
        username = self.driver.find_element(By.NAME, 'username')
        username.clear()
        username.send_keys('updated')
        first_name = self.driver.find_element(By.NAME, 'first_name')
        first_name.clear()
        first_name.send_keys('updated')
        last_name = self.driver.find_element(By.NAME, 'last_name')
        last_name.clear()
        last_name.send_keys('updated')
        email = self.driver.find_element(By.NAME, 'email')
        email.clear()
        email.send_keys('updated@email.com')
        phone_number = self.driver.find_element(By.NAME, 'phone_number')
        phone_number.clear()
        phone_number.send_keys('')
        self.driver.find_element(By.ID, 'updateUserButton').click()
        self.assertEqual(self.driver.title, 'Updating Information')

    ## Test edit user feature with first name too long
    def test_edit_user_feature_first_name_too_long(self):
        self.driver.get(self.live_server_url)
        self.driver.find_element(By.NAME, 'username').send_keys(self.user.username)
        self.driver.find_element(By.NAME, 'password').send_keys(self.password)
        self.driver.find_element(By.ID, 'loginButton').click()
        self.driver.find_element(By.ID, 'manageInfoButton').click()
        username = self.driver.find_element(By.NAME, 'username')
        username.clear()
        username.send_keys('updated')
        first_name = self.driver.find_element(By.NAME, 'first_name')
        first_name.clear()
        first_name.send_keys('test' * 101)
        last_name = self.driver.find_element(By.NAME, 'last_name')
        last_name.clear()
        last_name.send_keys('updated')
        email = self.driver.find_element(By.NAME, 'email')
        email.clear()
        email.send_keys('updated@email.com')
        phone_number = self.driver.find_element(By.NAME, 'phone_number')
        phone_number.clear()
        phone_number.send_keys('4-333-222-1111')
        self.driver.find_element(By.ID, 'updateUserButton').click()
        self.assertEqual(self.driver.title, 'Updating Information')

    ## Test edit user feature with last name too long
    def test_edit_user_feature_last_name_too_long(self):
        self.driver.get(self.live_server_url)
        self.driver.find_element(By.NAME, 'username').send_keys(self.user.username)
        self.driver.find_element(By.NAME, 'password').send_keys(self.password)
        self.driver.find_element(By.ID, 'loginButton').click()
        self.driver.find_element(By.ID, 'manageInfoButton').click()
        username = self.driver.find_element(By.NAME, 'username')
        username.clear()
        username.send_keys('updated')
        first_name = self.driver.find_element(By.NAME, 'first_name')
        first_name.clear()
        first_name.send_keys('updated')
        last_name = self.driver.find_element(By.NAME, 'last_name')
        last_name.clear()
        last_name.send_keys('test' * 101)
        email = self.driver.find_element(By.NAME, 'email')
        email.clear()
        email.send_keys('updated@email.com')
        phone_number = self.driver.find_element(By.NAME, 'phone_number')
        phone_number.clear()
        phone_number.send_keys('4-333-222-1111')
        self.driver.find_element(By.ID, 'updateUserButton').click()
        self.assertEqual(self.driver.title, 'Updating Information')

    ## Test edit user feature with email too long
    def test_edit_user_feature_email_too_long(self):
        self.driver.get(self.live_server_url)
        self.driver.find_element(By.NAME, 'username').send_keys(self.user.username)
        self.driver.find_element(By.NAME, 'password').send_keys(self.password)
        self.driver.find_element(By.ID, 'loginButton').click()
        self.driver.find_element(By.ID, 'manageInfoButton').click()
        username = self.driver.find_element(By.NAME, 'username')
        username.clear()
        username.send_keys('updated')
        first_name = self.driver.find_element(By.NAME, 'first_name')
        first_name.clear()
        first_name.send_keys('updated')
        last_name = self.driver.find_element(By.NAME, 'last_name')
        last_name.clear()
        last_name.send_keys('updated')
        email = self.driver.find_element(By.NAME, 'email')
        email.clear()
        email.send_keys('test' * 151)
        phone_number = self.driver.find_element(By.NAME, 'phone_number')
        phone_number.clear()
        phone_number.send_keys('4-333-222-1111')
        self.driver.find_element(By.ID, 'updateUserButton').click()
        self.assertEqual(self.driver.title, 'Updating Information')

    ## Test edit user feature with email incorrectly formatted
    def test_edit_user_feature_email_incorrect_format(self):
        self.driver.get(self.live_server_url)
        self.driver.find_element(By.NAME, 'username').send_keys(self.user.username)
        self.driver.find_element(By.NAME, 'password').send_keys(self.password)
        self.driver.find_element(By.ID, 'loginButton').click()
        self.driver.find_element(By.ID, 'manageInfoButton').click()
        username = self.driver.find_element(By.NAME, 'username')
        username.clear()
        username.send_keys('updated')
        first_name = self.driver.find_element(By.NAME, 'first_name')
        first_name.clear()
        first_name.send_keys('updated')
        last_name = self.driver.find_element(By.NAME, 'last_name')
        last_name.clear()
        last_name.send_keys('updated')
        email = self.driver.find_element(By.NAME, 'email')
        email.clear()
        email.send_keys('incorrect_format')
        phone_number = self.driver.find_element(By.NAME, 'phone_number')
        phone_number.clear()
        phone_number.send_keys('4-333-222-1111')
        self.driver.find_element(By.ID, 'updateUserButton').click()
        self.assertEqual(self.driver.title, 'Updating Information')

    ## Test edit user feature success
    def test_edit_user_feature_success(self):
        self.driver.get(self.live_server_url)
        self.driver.find_element(By.NAME, 'username').send_keys(self.user.username)
        self.driver.find_element(By.NAME, 'password').send_keys(self.password)
        self.driver.find_element(By.ID, 'loginButton').click()
        self.driver.find_element(By.ID, 'manageInfoButton').click()
        username = self.driver.find_element(By.NAME, 'username')
        username.clear()
        username.send_keys('updated')
        first_name = self.driver.find_element(By.NAME, 'first_name')
        first_name.clear()
        first_name.send_keys('updated')
        last_name = self.driver.find_element(By.NAME, 'last_name')
        last_name.clear()
        last_name.send_keys('updated')
        email = self.driver.find_element(By.NAME, 'email')
        email.clear()
        email.send_keys('updated@email.com')
        phone_number = self.driver.find_element(By.NAME, 'phone_number')
        phone_number.clear()
        phone_number.send_keys('4-333-222-1111')
        self.driver.find_element(By.ID, 'updateUserButton').click()
        self.assertEqual(self.driver.title, 'Home')
